/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 *****************************************************************************
 **/
#include "CortexM3/CortexM3_Core_NIVIC.h"





/******************************************************************************/
/* Syntax           : ERROR_State NVIC_EnableIRQ(IRQn_Types IRQn)
 * Description      : Enable External Interrupts
 * Sync\Async       : synchronous
 * Parameters       : IRQn
 * Return value:    : ERROR_State
 * Note				: IRQn cannot be negative
 *******************************************************************************/
ERROR_State NVIC_EnableIRQ(IRQn_Types IRQn)
{
	ERROR_State Local_u8ErrorState=OK;
	if((u32)IRQn>=0 && (u32)IRQn<=59){
	NVIC->ISER[((u32)IRQn)/register_bits]=(1UL << (((u32)IRQn) % register_bits));
	}else{
		Local_u8ErrorState = NOT_OK;
	}
	return Local_u8ErrorState;
}










/******************************************************************************/
/* Syntax           : ERROR_State NVIC_DisableIRQ(IRQn_Types IRQn)
 * Description      : Disable External Interrupts
 * Sync\Async       : Synchronous
 * Parameters       : IRQn
 * Return value:    : ERROR_State
 *******************************************************************************/
ERROR_State NVIC_DisableIRQ(IRQn_Types IRQn)
{
	ERROR_State Local_u8ErrorState=OK;
	if((u32)IRQn>=0 && (u32)IRQn<=59){
	NVIC->ICER[((u32)IRQn)/register_bits]=(1UL << (((u32)IRQn) % register_bits));
	}else{
		Local_u8ErrorState = NOT_OK;
	}
	return Local_u8ErrorState;
}







/******************************************************************************/
/* Syntax           :
 * Description      :
 * Sync\Async       :
 * Parameters       :
 * Return value:    :
 *******************************************************************************/
void NVIC_SetPendingIRQ(IRQn_Types IRQn)
{
	if((u32)IRQn>=0){

	NVIC->ISPR[((u32)IRQn) >> 5]=(1UL << (((u32)IRQn) & 0x1F));
	}
}








/******************************************************************************/
/* Syntax           :
 * Description      :
 * Sync\Async       :
 * Parameters       :
 * Return value:    :
 *******************************************************************************/
void NVIC_ClearPendingIRQ(IRQn_Types IRQn)
{
	if((u32)IRQn>=0){

	NVIC->ICPR[((u32)IRQn) >> 5]=(1UL << (((u32)IRQn) & 0x1F));
	}
}












/******************************************************************************/
/* Syntax           :
 * Description      :
 * Sync\Async       :
 * Parameters       :
 * Return value:    :
 *******************************************************************************/
u32 NVIC_GetActive(IRQn_Types IRQn)
{
	if((u32)IRQn>=0){
	return ((NVIC->IABR[((u32)IRQn) >> 5] & (1UL << (((u32)IRQn) & 0x1F))) != (u32)0) ? 0UL: 1UL;
	}else
	{
		return 0;
	}
}






/******************************************************************************/
/* Syntax           :
 * Description      :
 * Sync\Async       :
 * Parameters       :
 * Return value:    :
 *******************************************************************************/
void NVIC_SetPriority(IRQn_Types IRQn, u32 Priority)
{

	if((u32)IRQn>=0){
		NVIC->IP[(u32)IRQn] = (((u8)Priority << (8 - NVIC_PRIO_BITS)) & (u32)0xFF);
	}else
	{
		/* Nothing */
	}
}



/******************************************************************************/
/* Syntax           :
 * Description      :
 * Sync\Async       :
 * Parameters       :
 * Return value:    :
 *******************************************************************************/
u32 NVIC_GetPriority(IRQn_Types IRQn)
{
	if((u32)IRQn>=0){
		return (NVIC->IP[(u32)IRQn] >> (8 - NVIC_PRIO_BITS));
	}else
	{
		return 0;
	}
}
